# Generated by Django 3.2.12 on 2022-09-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
