# Generated by Django 3.2.12 on 2022-09-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='star',
            new_name='star_again',
        ),
    ]
