# Generated by Django 3.2.12 on 2022-09-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_star_movie_star_again'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='star_again',
        ),
    ]
