# Generated by Django 3.2.12 on 2022-09-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_star_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star_again',
            field=models.CharField(default='***', max_length=20),
        ),
    ]
